CREATE TABLE IF NOT EXISTS users (
	user_id BIGINT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	username VARCHAR(100) NOT NULL UNIQUE,
	full_name VARCHAR(255) NOT NULL,
	aadhaar_number VARCHAR(20) NOT NULL UNIQUE,
	role ENUM('ADMIN','USER') NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
	account_id BIGINT PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	balance DECIMAL(18,2) NOT NULL DEFAULT 0,
	CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transactions (
	txn_id BIGINT PRIMARY KEY AUTO_INCREMENT,
	from_account BIGINT NOT NULL,
	to_account BIGINT NULL,
	amount DECIMAL(18,2) NOT NULL,
	type ENUM('DEPOSIT','WITHDRAW','TRANSFER') NOT NULL,
	timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_txn_from FOREIGN KEY (from_account) REFERENCES accounts(account_id) ON DELETE CASCADE,
	CONSTRAINT fk_txn_to FOREIGN KEY (to_account) REFERENCES accounts(account_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS loans (
	loan_id BIGINT PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	amount DECIMAL(18,2) NOT NULL,
	reason VARCHAR(500) NOT NULL,
	duration INT NOT NULL,
	status ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
	applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_loans_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
); 